services:
  get-chat-id-bot:
    build:
      context: .
    environment:
      - TZ=Asia/Jerusalem
    platform: linux/amd64
    container_name: get-chat-id-bot
    volumes:
      - ./:/get-chat-id-bot
    command: ["python", "main.py"]
